version: "3.3"
services:
  web:
    image: praneethsvs/django-app:latest
    environment:
      - TZ=Europe/Minsk
    ports:
      - 8000:8000
    container_name: django
    networks:
      - django
    restart: unless-stopped

networks:
  django:
    driver: bridge





