version: "3.3"
services:
  web:
    image: praneethsvs/django-app:latest
    ports:
      - 8000:8000
    volumes:
      - /opt/app:/app
    container_name: django
    networks:
      - django
    restart: unless-stopped

networks:
  django: 
    driver: bridge




