ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
#FROM docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
FROM kibana:${ELASTIC_VERSION}
ENV TZ=UTC-3
# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
