---
- hosts: agent
  remote_user: test
  become: true
  vars_files: cred.yml
  tasks:
    - name: install java, git
      ansible.builtin.dnf:
        name:
          - java-17-openjdk
          - git
        state: present

    - name: Create /var/lib/jenkins
      ansible.builtin.file:
        path: /var/lib/jenkins
        state: directory
        recurse: yes
        owner: test
        group: test

    - name: install yum-utils
      ansible.builtin.yum:
        name:
          - yum-utils
        state: present

    - name: Add repo
      ansible.builtin.command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: install docker
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Ensure systemd daemon reloaded
      command: systemctl daemon-reload

    - name: Ensure Docker service is enabled and started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add the user 'test' to the group 'docker'
      ansible.builtin.user:
        name: test
        groups: docker
        append: yes

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /var/run/docker.sock
        owner: root
        group: docker
        mode: '0666'
    
    - name: Download and install filebeat
      ansible.builtin.yum:
        name: https://mirrors.huaweicloud.com/filebeat/7.10.2/filebeat-7.10.2-x86_64.rpm
        state: present
        disable_gpg_check: true

    - name: Copy filebeat.yml
      ansible.builtin.copy:
        src: /home/test/filebeat.yml
        dest: /etc/filebeat/filebeat.yml

    - name: Filebeat start and enable
      service:
        name: filebeat
        state: started
        enabled: yes

    - name: Create group node_exporter
      ansible.builtin.group:
        name: node_exporter
        state: present
        system: true

    - name: Create node_exporter user
      ansible.builtin.user:
        name: node_exporter
        group: node_exporter
        system: true

    - name: Download and unarchive node_exporter
      ansible.builtin.unarchive:
        src:  https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz
        dest: /home/test/
        remote_src: yes

    - name: Copy node_exporter to /usr/bin/
      ansible.builtin.copy:
        src: /home/test/node_exporter-1.8.1.linux-amd64/node_exporter
        dest: /usr/bin/
        owner: node_exporter
        group: node_exporter
        remote_src: true

    - name: Change file permissions
      ansible.builtin.file:
        path: /usr/bin/node_exporter
        mode: '0755'

    - name: Copy node_exporter.service
      ansible.builtin.copy:
        src: /home/test/node_exporter.service
        dest: /etc/systemd/system/node_exporter.service

    - name: System daemon-reload and started node_exporter
      ansible.builtin.systemd_service:
        state: started
        name: node_exporter.service
        daemon_reload: true
        enabled: true
     
    - name: Open port 9100
      ansible.builtin.command:
        cmd: firewall-cmd --zone=public --add-port=9100/tcp --permanent

    - name: Reload firewall
      ansible.builtin.command:
        cmd: firewall-cmd --reload



