ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
#FROM docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
FROM logstash:${ELASTIC_VERSION}
ENV TZ=UTC-3
# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
